exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

main/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import *
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', ViewAbout.as_view(), name='about'),
    path('contacts/', ViewContacts.as_view(), name='contacts'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('service/', ProductList.as_view(), name='service'),
    path('create_service/', CreateProduct.as_view(), name='create_service'),
    path('add_to_basket/<int:product_id>/', AddToBasketView.as_view(), name='add_to_basket'),
    path('register/', RegisterView.as_view(), name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class AdvUser(AbstractUser):
    basket = models.ManyToManyField('Product', blank=True, related_name='basket')

    class Meta:
        pass

class Product(models.Model):
    description = models.TextField(verbose_name='Описание товара')
    photo = models.ImageField(upload_to='media/', default=None, verbose_name='Фото товара')

main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Product, AdvUser


class CreateProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'photo')


class RegistrationForm(UserCreationForm):
    class Meta:
        model = AdvUser
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView
from .models import *
from .forms import CreateProductForm, RegistrationForm


def index(request):
    return render(request, 'main/index.html')

class LoginView(LoginView):
    template_name = 'main/login.html'
    success_url = reverse_lazy('main:create_service')
class ViewAbout(TemplateView):
    template_name = 'main/about.html'

class ViewContacts(TemplateView):
    template_name = 'main/contacts.html'

class ProductList(ListView):
    model = Product
    template_name = 'main/service.html'
    context_object_name = 'products'

class CreateProduct(CreateView):
    model = Product
    template_name = 'main/create_product.html'
    form_class = CreateProductForm
    success_url = reverse_lazy('main:service')

class BasketView(TemplateView):
    template_name = 'main/basket.html'

class AddToBasketView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        product_id = kwargs.get('product_id')
        product = get_object_or_404(Product, id=product_id)
        user = self.request.user

        if product not in user.basket.all():
            user.basket.add(product)
            return redirect('main:service')
        else:
            return HttpResponseBadRequest("Продукт уже находиться в корзине")

class RegisterView(View):
    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        return render(request, 'main/register.html', {'form': form})
    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:index')
        return render(request, 'main/register.html', {'form': form})

main/templates/layout/basic.html
{% load static %}{% load bootstrap4 %}
<!DOCTYPE html><html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
<header>
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</header>
<body>
{% if user.is_authenticated %}
    <ul class="dropdown_menu">
        <a class="item_menu" href="{% url 'main:index' %}">Главная</a>
        <a class="item_menu" href="{% url 'main:service' %}">Услуги</a>
        <a class="item_menu" href="{% url 'main:about' %}">О нас</a>
        <a class="item_menu" href="{% url 'main:contacts' %}">Контакты</a>
        <a class="item_menu" href="{% url 'main:create_service' %}">Добавить услугу</a>
        <a class="item_menu" href="{% url 'main:basket' %}">Ваша корзина</a>
        <a class="item_menu" href = "{% url 'main:logout' %}">Выйти</a>
    </ul>
{% else %}
    <ul class="dropdown_menu">
        <a class="item_menu" href="{% url 'main:index' %}">Главная</a>
        <a class="item_menu" href="{% url 'main:service' %}">Услуги</a>
        <a class="item_menu" href="{% url 'main:about' %}">О нас</a>
        <a class="item_menu" href="{% url 'main:contacts' %}">Контакты</a>
        <a class="item_menu" href="{% url 'main:login' %}">Войти</a>
        <a class="item_menu" href="{% url 'main:register' %}">Зарегистрироваться</a>
    </ul>
{% endif %}
{% block content%}

{% endblock %}
</body>

main/templates/main/about.html
{% extends "layout/basic.html" %}
{% block content %}
<h4> Мы занимаемся создание товаров для дома</h4>
{% endblock %}

main/templates/main/basket.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <h2>Ваша корзина добавленных услуг:</h2>
    {% if user.is_authenticated %}
        {% if user.basket.all %}
            <ul>
                {% for product in user.basket.all %}
                    <li><b>Описание товара:</b> {{ product.description }}</li>
                    <b>Изображение товара:</b> <img src="{{ product.photo.url }}" width="300px" height="300px">
                {% endfor %}
            </ul>
        {% else %}
            <p>Ваша корзина пуста</p>
        {% endif %}
    {% else %}
        <p>Вы не авторизованы</p>
    {% endif %}
{% endblock %}

main/templates/main/contacts.html
{% extends "layout/basic.html" %}
{% load static %}
{% block content %}
<h2>Здесь находятся наши контакты: </h2>
<h3>Телефон: +7 983 233 41 12</h3>
<h3>Электронная почта: mail@gmail.com</h3>
{% endblock %}

main/templates/main/create_product.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <h1>Создание нового товара</h1>
        {{form.as_p}}
    {% buttons submit='Создать товар' %} {% endbuttons %}
</form>
{% else %}
<h3>Авторизуйтесь в системе, чтобы создать товар</h3>
{% endif %}
{% endblock %}

main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% block content %}
<h1>Это сайт компании ****</h1>
{% endblock %}

main/templates/main/login.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    {% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endblock %}

main/templates/main/register.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <h2>Регистрация</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
  </form>
{% endblock %}

main/templates/main/service.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
{% if products %}
    {% for product in products %}
        <p><b>Описание товара:</b> {{ product.description }}</p>
        <b>Изображение товара:</b> <img src="{{ product.photo.url }}" width="300px" height="300px">
        {% if user.is_authenticated %}
            <br>
            {% if product in user.advuser.basket.all %}
                <p>Уже в корзине</p>
            {% else %}
                <form method="post" action="{% url 'main:add_to_basket' product.id %}">
                    {% csrf_token %}
                    <button type="submit">Добавить в корзину</button>
                </form>
            {% endif %}
        {% endif %}
    {% endfor %}
{% else %}
    <h3>На данный момент услуг нет</h3>
{% endif %}
{% endblock %}